package hibernate.domain;
// Generated 13/10/2018 10:15:41 AM by Hibernate Tools 4.3.1



/**
 * Tutoriales generated by hbm2java
 */
public class Tutoriales  implements java.io.Serializable {


     private Integer idtutorial;
     private String titulo;
     private String tipo;
     private double precio;

    public Tutoriales() {
    }

    public Tutoriales(String titulo, String tipo, double precio) {
       this.titulo = titulo;
       this.tipo = tipo;
       this.precio = precio;
    }
   
    public Integer getIdtutorial() {
        return this.idtutorial;
    }
    
    public void setIdtutorial(Integer idtutorial) {
        this.idtutorial = idtutorial;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }




}


